# NB: Lowercase!
{% set name = "mapserver" %}
{% set version = "8.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.osgeo.org/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0830c43feefeca132171b429403716a2cbaef0626d439f00e8a3a27a877724fe
  patches:
    - 0001-Fix-compilation-errors-with-libxml2-2.12.patch

build:
  number: 0
  # Any volunteers? :)
  skip: true  # [win or ppc64le]
  run_exports:
    # Presently libmapserver.so.2 is linked to libmapserver.so.x.y.z
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config  # [not win]
  host:
    - python
    - pip
    - cairo
    - fribidi
    - freetype
    - geos
    - giflib
    - harfbuzz
    - libjpeg-turbo
    - libcurl
    - libgdal
    - libiconv
    - libpng
    - libpq
    - libxml2
    - mysql-devel
    - pixman
    - postgresql
    - proj
    - swig
    - zlib
  run:
    - python
    - cairo
    - fribidi
    - freetype
    - geos
    - giflib
    - harfbuzz
    - libjpeg-turbo
    - libcurl
    - libgdal
    - libiconv
    - libpng
    - libxml2
    - mysql-libs
    - pixman
    - proj
    - zlib

test:
  imports:
    - mapscript  # [ not osx ]
  commands:
    - mapserv -v

about:
  home: https://mapserver.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Platform for publishing spatial data and interative mapping.
  description: |
    MapServer is an Open Source platform for publishing spatial data and
    interactive mapping applications to the web. MapServer is not a
    full-featured GIS system, nor does it aspire to be
  doc_url: https://mapserver.org/documentation.html
  dev_url: https://github.com/MapServer/MapServer

extra:
  recipe-maintainers:
    - akrherz
    - hobu
    - msmitherdc
